<?xml version="1.0" encoding="UTF-8"?>
<project xmlns="http://maven.apache.org/POM/4.0.0"
         xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
         xsi:schemaLocation="http://maven.apache.org/POM/4.0.0 http://maven.apache.org/xsd/maven-4.0.0.xsd">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>org.hastingtx.empire</groupId>
    <artifactId>empire-parent</artifactId>
    <version>0.1.0-SNAPSHOT</version>
  </parent>
  <artifactId>empire-engine</artifactId>
  <name>empire-engine</name>
  <dependencies>
    <dependency><groupId>net.jqwik</groupId><artifactId>jqwik</artifactId></dependency>
  </dependencies>
</project>
